apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api-sinerror-deployment
  labels:
    app: mlops-api-sinerror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api-sinerror
  template:
    metadata:
      labels:
        app: mlops-api-sinerror
    spec:
      containers:
      - name: mlops-api-sinerror
        image: gcr.io/sim2025-476817/mlops-api-sinerror:latest
        ports:
        - containerPort: 5000


