apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-web-sinerror-deployment
  labels:
    app: mlops-web-sinerror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-web-sinerror
  template:
    metadata:
      labels:
        app: mlops-web-sinerror
    spec:
      containers:
      - name: mlops-web-sinerror
        image: gcr.io/sim2025-476817/mlops-web-sinerror:latest 
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: http://mlops-api-sinerror-service:5000/predict